### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by RyanRHall** [RodCardenas/Flow-DIY#2]
Some of your links are broken. Make sure these work or remove them if they don't have any content to point to!

**Comment by RyanRHall** [comment]
I take it back -- don't remove them. Add the the component hierarchy and flux structure pages!

**Comment by RodCardenas** [comment]
Files with initial expectations have been created and the links in the readme have been updated pointing to the newly created files.

Flux Structure page is in development.
