### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by RyanRHall** [RodCardenas/Flow-DIY#4]
I would rename Phase 2 to bonus, and get rid of the phase 1 header.

Also, 2 days to "start styling" ?? Definitely not what we want. We should be styling all components to completion as we go. Instead, I would suggest reserving 1 day to "Page Layout" -- in which you position and coordinate components. Distribute the other day of styling into the other phases appropriately.

**Comment by RodCardenas** [comment]
Phase 2 renamed to bonus and modified timeline to comply with styling suggestion. Extra day was distributed to MVP's sections 2 and 3 (the Project and Step models implementation.)
